/**
 * AI Output Validation Engine for FormatAI
 *
 * Implements strict Quality-Gate Validation for AI Polish outputs:
 * 
 * Flow:
 * FormatAI Result
 *      ↓
 * AI Polish
 *      ↓
 * AI Output ❌
 *      ↓
 * Validation FAILED
 *      ↓
 * Discard AI Output
 *      ↓
 * Restore/Keep FormatAI Result
 *      ↓
 * Preview remains unchanged
 */

import {
  parseDocumentBlocks,
  compareDocumentBlocks,
  type BlockComparisonResult,
} from "./blockIntegrity.ts";

export interface ValidationDetail {
  check: string;
  passed: boolean;
  message?: string;
}

export type AIErrorCategory =
  | "key_missing"
  | "invalid_key"
  | "rate_limit"
  | "timeout"
  | "network"
  | "truncated"
  | "malformed";

export interface AIPolishValidationResult {
  isValid: boolean;
  score: number; // 0 to 100
  errors: string[];
  warnings: string[];
  discardReason?: string;
  errorCategory?: AIErrorCategory;
  blockComparison?: BlockComparisonResult;
  details: {
    nonEmpty: boolean;
    jsonComplete: boolean;
    notSeverelyTruncated: boolean;
    notSuspiciouslySmall: boolean;
    expectedBlockIdsPresent: boolean;
    noConversationalFiller: boolean;
    latexDelimitersBalanced: boolean;
    mathBracesBalanced: boolean;
    environmentsMatched: boolean;
    noDegradedOrEmptyMath: boolean;
    tablesWellFormed: boolean;
    codeFencesClosed: boolean;
    essentialMathPreserved: boolean;
    headingsPreserved: boolean;
    tablesPreserved: boolean;
    blocksPreserved?: boolean;
    charCountTolerancePassed?: boolean;
  };
}

/**
 * Validates the output generated by AI Polish against strict academic formatting rules.
 *
 * Checks:
 * 1. Non-empty: Not empty or whitespace-only
 * 2. JSON complete: If JSON formatted, parses completely without syntax/truncation errors
 * 3. Expected block IDs: Contains all expected blocks from baseline / chunk
 * 4. Not suspiciously small: Length is >= 60% of reference baseline length
 * 5. LaTeX syntax: Math delimiters, curly braces, and environments are closed & balanced
 *
 * @param aiOutput The raw text produced by the AI Polish engine
 * @param originalInput The user's original notes/input text
 * @param formatAiResult Optional current FormatAI Result for baseline fidelity comparison
 * @param expectedBlockIds Optional list of expected block IDs from document chunking
 */
export function validateAIPolishOutput(
  aiOutput: string | null | undefined,
  originalInput: string,
  formatAiResult?: string,
  expectedBlockIds?: string[]
): AIPolishValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  let errorCategory: AIErrorCategory | undefined;

  const details = {
    nonEmpty: true,
    jsonComplete: true,
    notSeverelyTruncated: true,
    notSuspiciouslySmall: true,
    expectedBlockIdsPresent: true,
    noConversationalFiller: true,
    latexDelimitersBalanced: true,
    mathBracesBalanced: true,
    environmentsMatched: true,
    noDegradedOrEmptyMath: true,
    tablesWellFormed: true,
    codeFencesClosed: true,
    essentialMathPreserved: true,
    headingsPreserved: true,
    tablesPreserved: true,
    blocksPreserved: true,
    charCountTolerancePassed: true,
  };

  // 1. Non-empty check
  if (!aiOutput || typeof aiOutput !== "string" || !aiOutput.trim()) {
    details.nonEmpty = false;
    errorCategory = "malformed";
    errors.push("AI Polish output is completely empty or whitespace only.");
    return {
      isValid: false,
      score: 0,
      errors,
      warnings,
      discardReason: "Empty AI output received.",
      errorCategory,
      details,
    };
  }

  const outputText = aiOutput.trim();
  const inputText = (originalInput || "").trim();
  const baselineText = (formatAiResult || "").trim();

  // 2. JSON Completeness check (if response is or contains JSON)
  if (
    (outputText.startsWith("{") && !outputText.includes("\n#")) ||
    (outputText.startsWith("[") && !outputText.includes("\n#")) ||
    /```(?:json)?\s*\{/.test(outputText)
  ) {
    try {
      let jsonPayload = outputText;
      const jsonMatch = outputText.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
      if (jsonMatch) {
        jsonPayload = jsonMatch[1].trim();
      }
      JSON.parse(jsonPayload);
    } catch (jsonErr: any) {
      details.jsonComplete = false;
      errorCategory = "malformed";
      errors.push(`Incomplete or malformed JSON output: ${jsonErr.message}`);
    }
  }

  // 3. Severe truncation / Suspiciously Small Check
  // Compare against original input and baseline FormatAI result
  const referenceLength = Math.max(inputText.length, baselineText.length);
  if (referenceLength > 80 && outputText.length < Math.min(60, referenceLength * 0.25)) {
    details.notSeverelyTruncated = false;
    details.notSuspiciouslySmall = false;
    if (!errorCategory) errorCategory = "truncated";
    errors.push(
      `Severe truncation detected: AI output length (${outputText.length} chars) is drastically smaller than baseline (${referenceLength} chars).`
    );
  } else if (referenceLength > 100 && outputText.length < referenceLength * 0.60) {
    details.notSuspiciouslySmall = false;
    if (!errorCategory) errorCategory = "truncated";
    errors.push(
      `Suspiciously small output: AI output length (${outputText.length} chars) dropped below 60% of baseline (${referenceLength} chars).`
    );
  }

  // 4. Expected Block ID Verification (if chunks/blocks are tagged)
  if (expectedBlockIds && expectedBlockIds.length > 0) {
    const formattedBlocks = parseDocumentBlocks(outputText);
    const formattedBlockIds = new Set(formattedBlocks.map((b) => b.id));
    
    // Also check substantive content matching in case IDs shifted
    const substantiveMatches = expectedBlockIds.filter((id) => {
      if (formattedBlockIds.has(id)) return true;
      // Check if the substantive text of that block is still retained in outputText
      return outputText.includes(id);
    });

    if (substantiveMatches.length < expectedBlockIds.length * 0.70) {
      details.expectedBlockIdsPresent = false;
      if (!errorCategory) errorCategory = "truncated";
      const missingCount = expectedBlockIds.length - substantiveMatches.length;
      errors.push(
        `Expected block ID verification failed: ${missingCount} of ${expectedBlockIds.length} expected content blocks are missing in output.`
      );
    }
  }

  // 5. Conversational AI Slop / Assistant Refusal check
  const conversationalLeadPatterns = [
    /^(?:I am sorry|I'm sorry|As an AI|As a language model|I cannot fulfill|I apologize)\b/i,
    /^(?:Here is|Here are|Certainly!|Sure!|Sure,|Below is|Here's) (?:the |your |a )?(?:cleaned|formatted|typeset|latex|revised|polished|academic|converted|result)/i,
    /^(?:I have|I've) (?:reformatted|cleaned|converted|typeset|updated) your (?:notes|text|formulas)/i,
  ];

  for (const pattern of conversationalLeadPatterns) {
    if (pattern.test(outputText)) {
      details.noConversationalFiller = false;
      errors.push("AI Polish output contains assistant conversational preamble/refusal instead of document text.");
      break;
    }
  }

  const conversationalTailPatterns = [
    /(?:I hope this helps|Let me know if you need anything else|Feel free to ask|Happy studying)[.!]?\s*$/i,
    /(?:Let me know if you would like me to|If you have further questions)[^.\n]*[.!]?\s*$/i,
  ];

  for (const pattern of conversationalTailPatterns) {
    if (pattern.test(outputText)) {
      warnings.push("AI output contains conversational closing statement.");
    }
  }

  // 4. LaTeX Delimiter Balance Checks
  // A. Display math $$ ... $$
  const doubleDollarMatches = (outputText.match(/(?<!\\)\$\$/g) || []).length;
  if (doubleDollarMatches % 2 !== 0) {
    details.latexDelimitersBalanced = false;
    errors.push(`Unmatched display equation delimiter '$$' (found ${doubleDollarMatches} odd count).`);
  }

  // B. Display math \[ ... \]
  const openBrackets = (outputText.match(/(?:\\)+\[/g) || []).length;
  const closeBrackets = (outputText.match(/(?:\\)+\]/g) || []).length;
  if (openBrackets !== closeBrackets) {
    details.latexDelimitersBalanced = false;
    errors.push(`Unmatched displayed equation delimiters: ${openBrackets} '\[' vs ${closeBrackets} '\]'.`);
  }

  // C. Inline math \( ... \)
  const openParens = (outputText.match(/(?:\\)+\(/g) || []).length;
  const closeParens = (outputText.match(/(?:\\)+\)/g) || []).length;
  if (openParens !== closeParens) {
    details.latexDelimitersBalanced = false;
    errors.push(`Unmatched inline math delimiters: ${openParens} '\(' vs ${closeParens} '\)'.`);
  }

  // D. Single $ inline math (excluding $$)
  const strippedOfDoubleDollar = outputText.replace(/(?<!\\)\$\$[\s\S]*?(?<!\\)\$\$/g, "");
  const singleDollarMatches = (strippedOfDoubleDollar.match(/(?<!\\)\$/g) || []).length;
  if (singleDollarMatches % 2 !== 0) {
    details.latexDelimitersBalanced = false;
    errors.push(`Unmatched inline dollar delimiter '$' (found ${singleDollarMatches} odd count).`);
  }

  // 5. LaTeX Formula Braces and Syntax Checks
  const mathExpressions: string[] = [];

  // Display equations
  const displayDollarRegex = /\$\$([\s\S]*?)\$\$/g;
  let match: RegExpExecArray | null;
  while ((match = displayDollarRegex.exec(outputText)) !== null) {
    mathExpressions.push(match[1]);
  }

  const bracketDisplayRegex = /\\\[([\s\S]*?)\\\]/g;
  while ((match = bracketDisplayRegex.exec(outputText)) !== null) {
    mathExpressions.push(match[1]);
  }

  // Inline equations
  const parenInlineRegex = /\\\(([\s\S]*?)\\\)/g;
  while ((match = parenInlineRegex.exec(outputText)) !== null) {
    mathExpressions.push(match[1]);
  }

  const singleDollarRegex = /(?<!\$)\$(?!\$)([^\$\n]+?)(?<!\$)\$(?!\$)/g;
  while ((match = singleDollarRegex.exec(strippedOfDoubleDollar)) !== null) {
    mathExpressions.push(match[1]);
  }

  // Check curly brace balance and empty math blocks in each extracted math formula
  let emptyMathCount = 0;
  for (const math of mathExpressions) {
    const trimmed = math.trim();
    if (!trimmed || trimmed === "\\text{}" || trimmed === "{}" || trimmed === "\\quad") {
      emptyMathCount++;
      continue;
    }

    // Check curly braces { ... } balance
    let braceDepth = 0;
    for (let i = 0; i < math.length; i++) {
      if (math[i] === "{" && (i === 0 || math[i - 1] !== "\\")) {
        braceDepth++;
      } else if (math[i] === "}" && (i === 0 || math[i - 1] !== "\\")) {
        braceDepth--;
      }
      if (braceDepth < 0) {
        break;
      }
    }

    if (braceDepth !== 0) {
      details.mathBracesBalanced = false;
      const snippet = math.length > 40 ? math.slice(0, 37) + "..." : math;
      errors.push(`Unbalanced curly braces '{' in math formula: "${snippet}"`);
      break;
    }
  }

  if (emptyMathCount > 2) {
    details.noDegradedOrEmptyMath = false;
    warnings.push(`Detected ${emptyMathCount} empty LaTeX equation placeholders ($$ $$).`);
  }

  // 6. LaTeX Environment Matching: \begin{env} vs \end{env}
  const begins = (outputText.match(/\\begin\{([^}]+)\}/g) || []).map((m) =>
    m.replace(/\\begin\{([^}]+)\}/, "$1")
  );
  const ends = (outputText.match(/\\end\{([^}]+)\}/g) || []).map((m) =>
    m.replace(/\\end\{([^}]+)\}/, "$1")
  );

  if (begins.length !== ends.length) {
    details.environmentsMatched = false;
    errors.push(`Mismatched LaTeX environments: ${begins.length} \\begin vs ${ends.length} \\end.`);
  } else {
    for (let i = 0; i < begins.length; i++) {
      if (!ends.includes(begins[i])) {
        details.environmentsMatched = false;
        errors.push(`Unclosed LaTeX environment \\begin{${begins[i]}}.`);
        break;
      }
    }
  }

  // 7. Markdown Code Fences Check
  const codeFenceCount = (outputText.match(/^```/gm) || []).length;
  if (codeFenceCount % 2 !== 0) {
    details.codeFencesClosed = false;
    errors.push(`Unclosed markdown code block fence (found ${codeFenceCount} backtick fences).`);
  }

  // 8. Markdown Table Structural Integrity Check
  const lines = outputText.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith("|") && line.endsWith("|")) {
      if (i + 1 < lines.length) {
        const nextLine = lines[i + 1].trim();
        if (
          !line.includes("---") &&
          nextLine.startsWith("|") &&
          !nextLine.includes("---") &&
          !lines.slice(Math.max(0, i - 1), i).some((l) => l.trim().includes("---"))
        ) {
          warnings.push(`Markdown table near line ${i + 1} may be missing a header separator row (|---|---|).`);
        }
      }
    }
  }

  // 9. Essential Math / Statistical Symbols Preservation
  const keySymbols = ["\\sigma", "\\mu", "\\bar{X}", "\\hat{p}", "SE(", "Var(", "Z ="];
  const presentInInput = keySymbols.filter((sym) => inputText.includes(sym) || baselineText.includes(sym));
  if (presentInInput.length >= 2) {
    const retainedInOutput = presentInInput.filter(
      (sym) => outputText.includes(sym) || outputText.includes(sym.toLowerCase())
    );
    if (retainedInOutput.length === 0) {
      details.essentialMathPreserved = false;
      errors.push("AI Polish dropped all key mathematical and statistical formulas present in the baseline document.");
    }
  }

  // 10. Headings Preservation Check (Rule 8: Headings hierarchy must be preserved)
  if (baselineText) {
    const baselineHeadingMatches = (baselineText.match(/^#{1,4}\s+.+$/gm) || []).length;
    const outputHeadingMatches = (outputText.match(/^#{1,4}\s+.+$/gm) || []).length;
    if (baselineHeadingMatches >= 3 && outputHeadingMatches === 0) {
      details.headingsPreserved = false;
      errors.push(`AI Polish dropped all section headings (baseline had ${baselineHeadingMatches} headings).`);
    }
  }

  // 11. Tables Preservation Check (Rule 8: Tables must be preserved)
  if (baselineText) {
    const baselineHasTable = /\|[^\n]+\|\r?\n\|[\s-:]+\|\r?\n/.test(baselineText);
    const outputHasTable = /\|[^\n]+\|\r?\n\|[\s-:]+\|\r?\n/.test(outputText);
    if (baselineHasTable && !outputHasTable) {
      details.tablesPreserved = false;
      errors.push("AI Polish dropped Markdown tables present in the baseline document.");
    }
  }

  // 12. Block-level Integrity & ±2% Character Count Tolerance Check (Audit Requirements 3, 4, 5)
  const sourceRefText = baselineText || inputText;
  let blockComparison: BlockComparisonResult | undefined;

  if (sourceRefText) {
    const origBlocks = parseDocumentBlocks(sourceRefText);
    const formBlocks = parseDocumentBlocks(outputText);
    blockComparison = compareDocumentBlocks(origBlocks, formBlocks, 2.0);

    details.blocksPreserved = blockComparison.missingBlocks.length === 0;
    details.charCountTolerancePassed = blockComparison.tolerancePassed;

    if (blockComparison.missingBlocks.length > 0) {
      const missingCount = blockComparison.missingBlocks.length;
      errors.push(
        `Block integrity failure: ${missingCount} content block(s) dropped during formatting (${blockComparison.flags[0] || "missing content"}).`
      );
    }

    if (!blockComparison.tolerancePassed) {
      errors.push(
        `Content preservation failure: Substantive character count drop exceeds ±2% tolerance (Original: ${blockComparison.originalSubstantiveChars}, Formatted: ${blockComparison.formattedSubstantiveChars}, Change: ${blockComparison.charCountDifferencePercent.toFixed(1)}%).`
      );
    }
  }

  // Compute validation score
  const totalChecks = Object.keys(details).length;
  const passedChecks = Object.values(details).filter(Boolean).length;
  const rawScore = (passedChecks / totalChecks) * 100 - warnings.length * 3;
  const finalScore = Math.max(0, Math.min(100, Math.round(rawScore)));

  const isValid = errors.length === 0 && finalScore >= 75;

  let discardReason: string | undefined;
  if (!isValid) {
    discardReason = errors[0] || "AI Polish output failed mathematical and formatting validation checks.";
    if (!errorCategory) {
      errorCategory = "malformed";
    }
  }

  return {
    isValid,
    score: finalScore,
    errors,
    warnings,
    discardReason,
    errorCategory,
    blockComparison,
    details,
  };
}

/**
 * Generates structured validation feedback for controlled AI repair re-prompting.
 */
export function formatValidationFeedback(validation: AIPolishValidationResult): string {
  const issues = validation.errors.map((e) => `• ${e}`).join("\n");
  return `Your previous output failed automated academic quality-gate validation because:
${issues}

Repair Instructions:
1. Preserve the existing FormatAI baseline structure completely.
2. Fix ONLY the formatting/validation problems identified above.
3. Do NOT omit any sections, tables, lists, or formulas.
4. Ensure all LaTeX math delimiters ($$, \\[, \\], \\(, \\), $) and braces { } are perfectly balanced.
5. Return the full repaired Markdown directly with NO conversational filler.`;
}
