import { ManagerConfig, ProviderConfig } from "./types.ts";
import { CLOUDFLARE_DEFAULT_MODELS } from "./adapters/CloudflareAdapter.ts";

export const DEFAULT_MANAGER_CONFIG: ManagerConfig = {
  mode: "automatic",
  activeProviderId: "gemini",
  activeModel: "gemini-2.5-flash",
  enableFallback: true,
  freeOnlyMode: true, // Safe default: Free-only mode = ON
  billingMode: "free_only",
  enableModelFallback: true,
  defaultTimeoutMs: 45000,
};

export function getInitialProviders(): ProviderConfig[] {
  return [
    {
      id: "gemini",
      name: "Google Gemini",
      enabled: true, // Primary provider enabled by default
      priority: 1,
      apiKeys: [],
      selectedModel: "gemini-2.5-flash",
      availableModels: [
        {
          id: "gemini-2.5-flash",
          name: "Gemini 2.5 Flash",
          contextWindow: 1048576,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "High speed, large context, standard for LaTeX equations.",
        },
        {
          id: "gemini-2.0-flash",
          name: "Gemini 2.0 Flash",
          contextWindow: 1048576,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Ultra-fast generation with high formatting accuracy.",
        },
        {
          id: "gemini-1.5-flash",
          name: "Gemini 1.5 Flash",
          contextWindow: 1048576,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Reliable fallback model.",
        },
        {
          id: "gemini-2.5-pro",
          name: "Gemini 2.5 Pro",
          contextWindow: 2097152,
          isFree: false,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Advanced complex academic reasoning (Paid tier).",
        },
      ],
      maxRetries: 2,
      timeoutMs: 45000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 15,
          requestsPerDay: 1500,
          tokensPerMinute: 1000000,
        },
        notes: "15 RPM, 1500 RPD free tier without credit card requirement.",
      },
      notes: "Primary AI provider with direct Google Gemini integration.",
    },
    {
      id: "groq",
      name: "Groq",
      enabled: true,
      priority: 2,
      apiKeys: [],
      selectedModel: "llama-3.3-70b-versatile",
      availableModels: [
        {
          id: "llama-3.3-70b-versatile",
          name: "Llama 3.3 70B Versatile",
          contextWindow: 128000,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Exceptional mathematical and LaTeX formatting speeds.",
        },
        {
          id: "llama-3.1-8b-instant",
          name: "Llama 3.1 8B Instant",
          contextWindow: 128000,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Fastest response time for standard note restructuring.",
        },
        {
          id: "mixtral-8x7b-32768",
          name: "Mixtral 8x7B Instruct",
          contextWindow: 32768,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Strong mixture-of-experts model.",
        },
        {
          id: "gemma2-9b-it",
          name: "Gemma 2 9B IT",
          contextWindow: 8192,
          isFree: true,
          capabilities: ["text", "math", "json", "code"],
          description: "Lightweight instruction model from Google.",
        },
      ],
      maxRetries: 2,
      timeoutMs: 30000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 30,
          requestsPerDay: 14400,
          tokensPerMinute: 6000,
        },
        notes: "30 RPM on free tier with LPUs delivering hundreds of tokens/sec.",
      },
      notes: "High speed backup provider for instant fallback.",
    },
    {
      id: "openrouter",
      name: "OpenRouter",
      enabled: true,
      priority: 3,
      apiKeys: [],
      selectedModel: "meta-llama/llama-3.3-70b-instruct:free",
      availableModels: [
        {
          id: "meta-llama/llama-3.3-70b-instruct:free",
          name: "Llama 3.3 70B Instruct (Free)",
          contextWindow: 131072,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Popular high capability free open weights router.",
        },
        {
          id: "google/gemini-2.0-flash-exp:free",
          name: "Google Gemini 2.0 Flash Exp (Free)",
          contextWindow: 1048576,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Gemini 2.0 via OpenRouter free routing.",
        },
        {
          id: "deepseek/deepseek-r1:free",
          name: "DeepSeek R1 (Free)",
          contextWindow: 64000,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Reasoning model with deep mathematical proofs.",
        },
        {
          id: "mistralai/mistral-7b-instruct:free",
          name: "Mistral 7B Instruct (Free)",
          contextWindow: 32768,
          isFree: true,
          capabilities: ["text", "math", "json", "code"],
          description: "Fast free tier fallback.",
        },
      ],
      maxRetries: 2,
      timeoutMs: 40000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 20,
          requestsPerDay: 200,
        },
        notes: "Aggregates free endpoints with :free tag.",
      },
      notes: "Universal fallback router supporting dozens of free models.",
    },
    {
      id: "mistral",
      name: "Mistral",
      enabled: true,
      priority: 4,
      apiKeys: [],
      selectedModel: "mistral-small-latest",
      availableModels: [
        {
          id: "mistral-small-latest",
          name: "Mistral Small (Latest)",
          contextWindow: 32768,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Balanced reasoning, math, and code with free experiment tier.",
        },
        {
          id: "open-mistral-7b",
          name: "Open Mistral 7B",
          contextWindow: 32768,
          isFree: true,
          capabilities: ["text", "math", "json", "code"],
          description: "Fast instruction-following model.",
        },
        {
          id: "codestral-latest",
          name: "Codestral",
          contextWindow: 32768,
          isFree: true,
          capabilities: ["text", "math", "long_context", "code"],
          description: "Proficient in formal syntax and mathematical equations.",
        },
      ],
      maxRetries: 2,
      timeoutMs: 35000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 5,
          requestsPerDay: 1000,
        },
        notes: "La Plateforme free tier experimentation limits.",
      },
      notes: "European open-weights AI provider with strict privacy standards.",
    },
    {
      id: "cohere",
      name: "Cohere",
      enabled: true,
      priority: 5,
      apiKeys: [],
      selectedModel: "command-r",
      availableModels: [
        {
          id: "command-r",
          name: "Command R",
          contextWindow: 128000,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Command series model with large context and trial keys.",
        },
        {
          id: "command-light",
          name: "Command Light",
          contextWindow: 4096,
          isFree: true,
          capabilities: ["text", "math"],
          description: "Ultra-compact fast model.",
        },
      ],
      maxRetries: 1,
      timeoutMs: 35000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 10,
          requestsPerDay: 1000,
        },
        notes: "Free trial keys for developers.",
      },
      notes: "Enterprise-grade model provider.",
    },
    {
      id: "huggingface",
      name: "Hugging Face",
      enabled: true,
      priority: 6,
      apiKeys: [],
      selectedModel: "Qwen/Qwen2.5-72B-Instruct",
      availableModels: [
        {
          id: "Qwen/Qwen2.5-72B-Instruct",
          name: "Qwen 2.5 72B Instruct",
          contextWindow: 32768,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Top benchmark open model for math, formulas, and STEM notes.",
        },
        {
          id: "meta-llama/Llama-3.3-70B-Instruct",
          name: "Meta Llama 3.3 70B Instruct",
          contextWindow: 128000,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Meta flagship on HF inference serverless router.",
        },
      ],
      maxRetries: 2,
      timeoutMs: 45000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 10,
        },
        notes: "Serverless Inference API free with user HF Access Token.",
      },
      notes: "Direct access to thousands of open source models on Hugging Face.",
    },
    {
      id: "cloudflare",
      name: "Cloudflare Workers AI",
      enabled: true,
      priority: 7,
      apiKeys: [],
      selectedModel: "@cf/meta/llama-3.3-70b-instruct",
      availableModels: CLOUDFLARE_DEFAULT_MODELS,
      maxRetries: 2,
      timeoutMs: 40000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerDay: 10000,
        },
        notes: "10,000 free neurons daily on Cloudflare Workers AI free tier.",
      },
      notes: "Edge-hosted open models running on Cloudflare global network.",
    },
    {
      id: "custom",
      name: "Custom AI Endpoint",
      enabled: false, // Explicitly OFF by default
      priority: 8,
      apiKeys: [],
      selectedModel: "default-model",
      availableModels: [
        {
          id: "default-model",
          name: "Custom Local Model",
          contextWindow: 32768,
          isFree: true,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Self-hosted Ollama, LM Studio, vLLM, or custom proxy.",
        },
      ],
      maxRetries: 1,
      timeoutMs: 60000,
      customEndpoint: "http://localhost:11434/v1/chat/completions",
      billingMode: "free_only",
      notes: "Allows connecting local LLMs like Ollama or custom reverse proxies.",
    },
  ];
}
