import type { ManagerConfig, ProviderConfig } from "./types.ts";
import { CENTRAL_CATALOG } from "../../shared/centralModelCatalog.ts";

export const DEFAULT_MANAGER_CONFIG: ManagerConfig = {
  mode: "automatic",
  activeProviderId: "gemini",
  activeModel: "gemini-3.8-flash",
  enableFallback: true,
  freeOnlyMode: true, // Safe default: Free-only mode = ON
  billingMode: "free_only",
  enableModelFallback: true,
  defaultTimeoutMs: 45000,
};

export function getInitialProviders(): ProviderConfig[] {
  return [
    {
      id: "gemini",
      name: "Google Gemini",
      enabled: true, // Primary provider enabled by default
      priority: 1,
      apiKeys: [],
      selectedModel: "gemini-3.8-flash",
      availableModels: CENTRAL_CATALOG.gemini,
      maxRetries: 2,
      timeoutMs: 45000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 15,
          requestsPerDay: 1500,
          tokensPerMinute: 1000000,
        },
        notes: "Free tier — 15 RPM, 1,500 RPD without credit card requirement.",
      },
      notes: "Primary AI provider with direct Google Gemini integration.",
    },
    {
      id: "openai",
      name: "OpenAI",
      enabled: false,
      priority: 2,
      apiKeys: [],
      selectedModel: "gpt-4o-mini",
      availableModels: CENTRAL_CATALOG.openai || [],
      maxRetries: 2,
      timeoutMs: 45000,
      billingMode: "free_only",
      freeTier: {
        enabled: false,
        limits: {},
        notes: "Developer pay-as-you-go tier.",
      },
      notes: "Direct OpenAI integration supporting GPT-4o, GPT-4o Mini, and reasoning models.",
    },
    {
      id: "claude",
      name: "Anthropic Claude",
      enabled: false,
      priority: 3,
      apiKeys: [],
      selectedModel: "claude-3-5-haiku-latest",
      availableModels: CENTRAL_CATALOG.claude || [],
      maxRetries: 2,
      timeoutMs: 45000,
      billingMode: "free_only",
      freeTier: {
        enabled: false,
        limits: {},
        notes: "Anthropic API pay-as-you-go tier.",
      },
      notes: "Direct Anthropic Claude integration for advanced academic document formatting.",
    },
    {
      id: "groq",
      name: "Groq",
      enabled: true,
      priority: 4,
      apiKeys: [],
      selectedModel: "openai/gpt-oss-120b",
      availableModels: CENTRAL_CATALOG.groq,
      maxRetries: 2,
      timeoutMs: 30000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 30,
          requestsPerDay: 14400,
          tokensPerMinute: 6000,
        },
        notes: "Free tier — 30 RPM on Groq LPU with ultra-low latency.",
      },
      notes: "High speed backup provider for instant fallback on Groq LPUs.",
    },
    {
      id: "openrouter",
      name: "OpenRouter",
      enabled: true,
      priority: 3,
      apiKeys: [],
      selectedModel: "zai-org/glm-5.3-prime:free",
      availableModels: CENTRAL_CATALOG.openrouter,
      maxRetries: 2,
      timeoutMs: 40000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 20,
          requestsPerDay: 200,
        },
        notes: "Free tier — genuine $0 pricing verified endpoints.",
      },
      notes: "Universal fallback router supporting verified $0 free models.",
    },
    {
      id: "mistral",
      name: "Mistral",
      enabled: true,
      priority: 4,
      apiKeys: [],
      selectedModel: "mistral-medium-3.5",
      availableModels: CENTRAL_CATALOG.mistral,
      maxRetries: 2,
      timeoutMs: 35000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 5,
          requestsPerDay: 1000,
        },
        notes: "Free tier — La Plateforme experiment tier limits.",
      },
      notes: "European open-weights AI provider with strict privacy standards.",
    },
    {
      id: "cohere",
      name: "Cohere",
      enabled: true,
      priority: 5,
      apiKeys: [],
      selectedModel: "command-a-plus-05-2026",
      availableModels: CENTRAL_CATALOG.cohere,
      maxRetries: 1,
      timeoutMs: 35000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 20,
          requestsPerDay: 1000,
        },
        notes: "Free tier — Trial API key: 20 RPM, 1,000 monthly calls.",
      },
      notes: "Enterprise-grade model provider with developer trial keys.",
    },
    {
      id: "huggingface",
      name: "Hugging Face",
      enabled: true,
      priority: 6,
      apiKeys: [],
      selectedModel: "Qwen/Qwen3.8-27B",
      availableModels: CENTRAL_CATALOG.huggingface,
      maxRetries: 2,
      timeoutMs: 45000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerMinute: 10,
        },
        notes: "Free tier — Serverless Inference API with user HF Access Token.",
      },
      notes: "Serverless inference access to verified open source instruction models.",
    },
    {
      id: "cloudflare",
      name: "Cloudflare Workers AI",
      enabled: true,
      priority: 7,
      apiKeys: [],
      selectedModel: "@cf/zai-org/glm-5.3",
      availableModels: CENTRAL_CATALOG.cloudflare,
      maxRetries: 2,
      timeoutMs: 40000,
      billingMode: "free_only",
      freeTier: {
        enabled: true,
        limits: {
          requestsPerDay: 10000,
        },
        notes: "Free tier — 10,000 free neurons daily on Workers AI edge.",
      },
      notes: "Edge-hosted open models running on Cloudflare global network.",
    },
    {
      id: "custom",
      name: "Custom AI Endpoint",
      enabled: false, // Explicitly OFF by default
      priority: 8,
      apiKeys: [],
      selectedModel: "default-model",
      availableModels: [
        {
          id: "default-model",
          name: "Custom Local Model",
          provider: "custom",
          status: "active",
          free: true,
          isFree: true,
          apiAvailable: true,
          deprecated: false,
          retired: false,
          freeTier: "Local / custom unlimited",
          contextWindow: 32768,
          capabilities: ["text", "math", "long_context", "json", "code"],
          description: "Self-hosted Ollama, LM Studio, vLLM, or custom proxy.",
        },
      ],
      maxRetries: 1,
      timeoutMs: 60000,
      customEndpoint: "http://localhost:11434/v1/chat/completions",
      billingMode: "free_only",
      notes: "Allows connecting local LLMs like Ollama or custom reverse proxies.",
    },
  ];
}
